title: Spimoza.jl
description: The Standard Model as information geometry
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://uwbanjoman.github.io
baseurl: /Spinoza.jl

aux_links:
  GitHub: https://github.com/uwbanjoman/Spinoza.jl

color_scheme: light
